### ISSUE TITLE
hiprand_hcc.h doesn't look for rocrand.h at the right place

### ISSUE THREAD

**Issue by baerbock** [ROCm/tensorflow-upstream#347]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: git master
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: X
- Bazel version (if compiling from source): 0.20
- GCC/Compiler version (if compiling from source): gcc 8.2.1
- ROCm/MIOpen version: 2.1.0 / 1.7.1
- GPU model and memory: RX 470

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I had to patch my hip path
```
--- ./third_party/gpus/rocm_configure.bzl.old	2019-01-22 01:30:46.997847580 +0100
+++ ./third_party/gpus/rocm_configure.bzl	2019-01-22 02:22:13.238829474 +0100
@@ -378,7 +378,7 @@
             "hip_hcc",
             repository_ctx,
             cpu_value,
-            rocm_config.rocm_toolkit_path,
+            rocm_config.rocm_toolkit_path + "/hip/lib",
         ),
         "rocblas": _find_rocm_lib(
             "rocblas",
```
and I compile with `bazel build --config=noaws --config=opt --config=rocm --action_env=HIP_PLATFORM=hcc //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

The compilation runs for 500 seconds, compiles much stuff and then fails because it _can't find rocrand.h_?

**Any other info / logs**
```
ERROR: /build/tensorflow-git/src/tensorflow-upstream/tensorflow/stream_executor/BUILD:682:1: C++ compilation of rule '//tensorflow/stream_executor:rocm_platform' failed (Exit 1): crosstool_wrapper_driver_rocm failed: error executing command 
  (cd /build/.cache/bazel/_bazel_builduser/bf26ebc8ab19de7775c72f743b055f9c/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl \
    PWD=/proc/self/cwd \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/host/bin/tensorflow/stream_executor/_objs/rocm_platform/rocm_kernel.pic.d '-frandom-seed=bazel-out/host/bin/tensorflow/stream_executor/_objs/rocm_platform/rocm_kernel.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -iquote . -iquote bazel-out/host/genfiles -iquote bazel-out/host/bin -iquote external/com_google_absl -iquote bazel-out/host/genfiles/external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -iquote external/nsync -iquote bazel-out/host/genfiles/external/nsync -iquote bazel-out/host/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -iquote bazel-out/host/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/host/genfiles/external/local_config_sycl -iquote bazel-out/host/bin/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote bazel-out/host/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/host/genfiles/external/jpeg -iquote bazel-out/host/bin/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/host/genfiles/external/protobuf_archive -iquote bazel-out/host/bin/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/genfiles/external/com_googlesource_code_re2 -iquote bazel-out/host/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote bazel-out/host/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/host/genfiles/external/fft2d -iquote bazel-out/host/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote bazel-out/host/bin/external/highwayhash -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -iquote bazel-out/host/bin/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/host/genfiles/external/local_config_cuda -iquote bazel-out/host/bin/external/local_config_cuda -iquote external/local_config_rocm -iquote bazel-out/host/genfiles/external/local_config_rocm -iquote bazel-out/host/bin/external/local_config_rocm -isystem external/nsync/public -isystem bazel-out/host/genfiles/external/nsync/public -isystem bazel-out/host/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/host/genfiles/external/eigen_archive -isystem bazel-out/host/bin/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/host/genfiles/external/gif_archive/lib -isystem bazel-out/host/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/host/genfiles/external/protobuf_archive/src -isystem bazel-out/host/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/host/genfiles/external/farmhash_archive/src -isystem bazel-out/host/bin/external/farmhash_archive/src -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda -isystem bazel-out/host/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include -isystem external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include/crt -isystem external/local_config_rocm/rocm -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm -isystem bazel-out/host/bin/external/local_config_rocm/rocm -isystem external/local_config_rocm/rocm/rocm/include -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm/rocm/include -isystem bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include -isystem external/local_config_rocm/rocm/rocm/include/rocrand -isystem bazel-out/host/genfiles/external/local_config_rocm/rocm/rocm/include/rocrand -isystem bazel-out/host/bin/external/local_config_rocm/rocm/rocm/include/rocrand -g0 '-march=native' -g0 -DTENSORFLOW_USE_ROCM -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -D__HIP_PLATFORM_HCC__ -DEIGEN_USE_HIP -fno-canonical-system-headers -c tensorflow/stream_executor/rocm/rocm_kernel.cc -o bazel-out/host/bin/tensorflow/stream_executor/_objs/rocm_platform/rocm_kernel.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from bazel-out/host/genfiles/external/local_config_rocm/rocm/rocm/include/hiprand/hiprand.h:55,
                 from ./tensorflow/stream_executor/gpu/gpu_types.h:25,
                 from ./tensorflow/stream_executor/gpu/gpu_driver.h:30,
                 from ./tensorflow/stream_executor/gpu/gpu_kernel.h:25,
                 from tensorflow/stream_executor/rocm/rocm_kernel.cc:16:
bazel-out/host/genfiles/external/local_config_rocm/rocm/rocm/include/hiprand/hiprand_hcc.h:24:10: fatal error: rocrand.h: No such file or directory
 #include <rocrand.h>
          ^~~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 527.727s, Critical Path: 46.30s
INFO: 1858 processes: 1858 local.
```

**Comment by sunway513** [comment]
Hi @baerbock , we are working on enabling python3.7 based build for tensorflow-rocm project. Before that's fully functioning, can you use our docker based solutions? 
Here's our docker registry:
https://cloud.docker.com/u/rocm/repository/docker/rocm/tensorflow

**Comment by sunway513** [comment]
@baerbock , could you confirm if you were following our official doc to build TF-rocm from source? Link below:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-build-from-source.md

**Comment by ppanchad-amd** [comment]
Hi @baerbock. Closing ticket due to lack of activity. Please feel free to open another ticket if you still any questions/issues with the latest ROCm. Thanks!
